services:
  - type: web
    name: cadenza-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production 